# Generated by Django 2.2.4 on 2019-11-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('birth_month', models.CharField(max_length=10)),
                ('birth_day', models.CharField(max_length=10)),
                ('birth_year', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
