# Generated by Django 2.2.7 on 2019-12-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecoveryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverydatamodel',
            name='disabled',
            field=models.CharField(db_index=True, default='False', max_length=10),
        ),
        migrations.AddField(
            model_name='recoverydatamodel',
            name='employee_name',
            field=models.CharField(db_index=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='recoverydatamodel',
            name='error',
            field=models.CharField(db_index=True, default='No Error', max_length=100),
        ),
        migrations.AddField(
            model_name='recoverydatamodel',
            name='insert_date',
            field=models.CharField(db_index=True, default='2019-12-05', max_length=20),
        ),
        migrations.AddField(
            model_name='recoverydatamodel',
            name='log',
            field=models.CharField(db_index=True, default='Not In Process', max_length=100),
        ),
        migrations.AddField(
            model_name='recoverydatamodel',
            name='process_trigger',
            field=models.CharField(db_index=True, default='False', max_length=10),
        ),
        migrations.AddField(
            model_name='recoverydatamodel',
            name='recovery_attempt',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='recoverydatamodel',
            name='recovery_date',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='recoverydatamodel',
            name='recovery_month',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='recoverydatamodel',
            name='recoverydone',
            field=models.CharField(db_index=True, default='False', max_length=10),
        ),
        migrations.AddField(
            model_name='recoverydatamodel',
            name='recoveryemail',
            field=models.CharField(db_index=True, default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recoverydatamodel',
            name='birth_day',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recoverydatamodel',
            name='birth_month',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recoverydatamodel',
            name='birth_year',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recoverydatamodel',
            name='firstname',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recoverydatamodel',
            name='gender',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recoverydatamodel',
            name='lastname',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recoverydatamodel',
            name='password',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='recoverydatamodel',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='recoverydatamodel',
            name='proxy',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recoverydatamodel',
            name='username',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
